# Generated by Django 3.2.8 on 2021-10-13 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.CharField(max_length=120)),
                ('autor', models.CharField(max_length=120)),
                ('tag', models.CharField(max_length=120)),
                ('links', models.CharField(max_length=120)),
            ],
        ),
    ]
