# Generated by Django 3.2.8 on 2021-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='tag',
            field=models.CharField(choices=[('django', 'Django'), ('python', 'Python'), ('git', 'Git')], max_length=30),
        ),
    ]
